### ISSUE TITLE
Escaping issue in some path

### ISSUE THREAD

**Issue by a-n-d-i** [SteveLTN/https-portal#161]
Hi,

awesome project! 

I guess I found an escaping issue. Not too sure about the details but an underscore in a container name leads to the following error. Using a hyphen instead works fine.

```
environment:
    DOMAINS: 'abc.de -> http://abc_wordpress:80 #local, someotherdomain.rocks #local'
```

```
Error: Invalid descriptor abc.de -> http://abc_wordpress:80 #local
https-portal_1            | /opt/certs_manager/models/domain.rb:72:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:39:in `dir'
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:121:in `create_dir'
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:10:in `initialize'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:50:in `new'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:50:in `block in parse'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:49:in `map'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:49:in `parse'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:32:in `env_domains'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:3:in `domains'
https-portal_1            | 	from /opt/certs_manager/certs_manager.rb:11:in `setup'
https-portal_1            | 	from /etc/cont-init.d/20-setup:4:in `<main>'
```
Cheers, Andi

**Comment by SteveLTN** [comment]
Hi, could you try again with the newly release 1.4.3? The regex was refactored and underscore was somehow left out. Now it is fixed and added to the test :-)

**Comment by andreportela** [comment]
Hi! the release 1.4.3 has broken a domain name that I was using: `exam-ple.com`. It was working on 1.4.2 but started to throw the same error state above on 1.4.3.
```
Error: Invalid descriptor exam-ple -> https://192.168.1.1 #local
https-portal_1            | /opt/certs_manager/models/domain.rb:72:in `name': undefined method `[]' for nil:NilClass (NoMethodError)
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:39:in `dir'
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:121:in `create_dir'
https-portal_1            | 	from /opt/certs_manager/models/domain.rb:10:in `initialize'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:50:in `new'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:50:in `block in parse'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:49:in `map'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:49:in `parse'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:32:in `env_domains'
https-portal_1            | 	from /opt/certs_manager/lib/na_config.rb:3:in `domains'
https-portal_1            | 	from /opt/certs_manager/certs_manager.rb:11:in `setup'
https-portal_1            | 	from /etc/cont-init.d/20-setup:4:in `<main>'
```
I think that maybe the regular expression needs just another test case and a tiny tweak.

Congrats for the AWESOME project!!!! \o/

**Comment by SteveLTN** [comment]
Just released 1.4.4. Sorry for the inconvenience. Ah regex!!!

**Comment by rafael151** [comment]
Thanks @SteveLTN !

**Comment by a-n-d-i** [comment]
1.4.4 fixes the issue for me, thanks @SteveLTN !!

**Comment by a-n-d-i** [comment]
Just had a look at the commit for the fix, it might be more feature proof the escape the "-" with a backslash, thus turning it from a range operator to a literal in the regex class. That way, further added characters behind the "\-" don't break the regex :-) Dunno why/how it works with the "-" at the end, either ruby is treating the range as a literal because there's no upper limit given or it does some weird range...

**Comment by SteveLTN** [comment]
@a-n-d-i I'm not a regex expert, so I used https://regex101.com/ when i make changes. According to the site, when `-` is in the end, it is treated as a literal.

Anyway, I have tests covering the case, it should be fine :-)
